#!/bin/bash

calc_work_time()
{
	start=$(date +%s.%N)
	workTime=0
	workPhrase="$1:"
	
	while read line; do
	IFS=' ' read -a array <<<$line
		for index in "${!array[@]}"; do
			if [ ${array[index]} = $workPhrase ]; then
			workTime=$(($workTime+${array[index+1]}))
			fi
		done
	done < $2
	
	printf "$1 works: $workTime s\n"
	
	end=$(date +%s.%N)
	runtime=$(echo "$end - $start" | bc)
	printf "Calculation duration: $runtime ms\n"
}
